<a href="https://colab.research.google.com/github/2003Yash/SVD/blob/main/SVD_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import tensorflow as tf

In [39]:
W = tf.range(12, dtype=tf.float32)
W = tf.reshape(W, (4, 3))

In [40]:
W

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>

SVD

In [41]:
s, u, v = tf.linalg.svd(W, full_matrices=False) # s is E matrix

In [42]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.2446745e+01, 1.4640579e+00, 8.7649272e-07], dtype=float32)>

In [43]:
tf.linalg.diag(s)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.2446745e+01, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.4640579e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 8.7649272e-07]], dtype=float32)>

In [44]:
# Diagonal matrix from singular values
s_diag = tf.linalg.diag(s)

In [45]:
u

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.08351801, -0.83248097,  0.29955974],
       [ 0.31365085, -0.4490248 , -0.05763252],
       [ 0.54378384, -0.06556851, -0.7834127 ],
       [ 0.77391666,  0.3178885 ,  0.54148597]], dtype=float32)>

In [46]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.49757344,  0.7653458 , -0.40824807],
       [ 0.5739707 ,  0.06237779,  0.81649655],
       [ 0.65036786, -0.6405895 , -0.40824848]], dtype=float32)>

In [48]:
# Reconstruct the matrix using SVD components
W_reconstructed = tf.matmul(u, tf.matmul(s_diag, tf.transpose(v)))

In [49]:
W_reconstructed

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[7.8687930e-07, 1.0000013e+00, 1.9999999e+00],
       [2.9999993e+00, 3.9999995e+00, 4.9999986e+00],
       [6.0000000e+00, 6.9999995e+00, 7.9999995e+00],
       [8.9999981e+00, 9.9999981e+00, 1.0999997e+01]], dtype=float32)>

TRUNCATED SVD

In [50]:
s_t = s[:2]

In [51]:
s_diag

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.2446745e+01, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.4640579e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 8.7649272e-07]], dtype=float32)>

In [52]:
# Create a diagonal matrix from Et
s_t_diag = tf.linalg.diag(s_t)
s_t_diag

#here s and st are same values example: s_diag[0,0] is 2.24 but s_t_diag[0,0] is 22.4 but s_diag has e^1 so 1 decimal is moved but s_diag[1,1] and s_t_diag[1,1] are same since no e^0

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22.446745 ,  0.       ],
       [ 0.       ,  1.4640579]], dtype=float32)>

In [53]:
u.shape, s_diag.shape, tf.transpose(v).shape

(TensorShape([4, 3]), TensorShape([3, 3]), TensorShape([3, 3]))

In [54]:
u.shape, s_t_diag.shape, tf.transpose(v).shape # can't multiply since s_t should be 3x3

(TensorShape([4, 3]), TensorShape([2, 2]), TensorShape([3, 3]))

In [55]:
# Pad the diagonal matrix with zeros
s_t_diag = tf.pad(s_t_diag, [[0, 1], [0, 1]], mode="CONSTANT", constant_values=0)
s_t_diag

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[22.446745 ,  0.       ,  0.       ],
       [ 0.       ,  1.4640579,  0.       ],
       [ 0.       ,  0.       ,  0.       ]], dtype=float32)>

In [56]:
u.shape, s_t_diag.shape, tf.transpose(v).shape

(TensorShape([4, 3]), TensorShape([3, 3]), TensorShape([3, 3]))

In [57]:
W_truncated = tf.matmul(u, tf.matmul(s_t_diag, tf.transpose(v)))

In [58]:
W_reconstructed

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[7.8687930e-07, 1.0000013e+00, 1.9999999e+00],
       [2.9999993e+00, 3.9999995e+00, 4.9999986e+00],
       [6.0000000e+00, 6.9999995e+00, 7.9999995e+00],
       [8.9999981e+00, 9.9999981e+00, 1.0999997e+01]], dtype=float32)>

In [59]:
W_truncated

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[8.9406967e-07, 1.0000011e+00, 2.0000000e+00],
       [2.9999993e+00, 3.9999995e+00, 4.9999986e+00],
       [5.9999995e+00, 7.0000000e+00, 7.9999990e+00],
       [8.9999981e+00, 9.9999981e+00, 1.0999997e+01]], dtype=float32)>